site:
  title: Entra ID Dart Auth SDK Docs
  start_page: entra-id-dart-auth-sdk::index.adoc
  url: https://entra-id-dart-auth-sdk-docs.web.app/

content:
  sources:
    - url: ..
      branches: HEAD
      start_path: entra-id-dart-auth-sdk/docs/components/entra-id-dart-auth-sdk

ui:
  bundle:
    url: ./ui/antora-ui-custom/ui-bundle
    snapshot: true
