name: entra_id_dart_auth_sdk
description: A Dart SDK for Entra Id Authentication, enabling secure server-side authentication and user management for Dart-based backend applications.
version: 0.0.1-pre+2
repository: https://github.com/aortem/entra-id-dart-auth-sdk
license: BSD-3

environment:
  sdk: ^3.9.0

# Add regular dependencies here.

dependencies:

#------------------ STANDARD FEATURES---------------------------------

## There are three standard libraries provided by the Dart Team. 

  ds_standard_features: ^0.1.0

#------------------ ADDITIONAL FEATURES---------------------------------
  build_web_compilers: ^4.2.2
  jwt_generator: ^0.0.5
  web: ^1.1.1
  js_interop: ^0.0.1

#------------------ TESTING FEATURES---------------------------------

dev_dependencies:
  ds_tools_testing: ^0.0.9  # Standard Dart Team Testing Tools
  git_hooks: any

# Optional Local Hooks for development.
git_hooks:
  hooks:
    pre-commit: ./local_dev_tools/validate_commit.dart
    commit-msg: ./local_dev_tools/validate_commit_msg.dart
    pre-push: ./local_dev_tools/validate_branch.dart

false_secrets:
  - test/unit/core/entra_id_client_assertion.dart
